[profile.default]
src = "src"
out = "out"
libs = ["lib"]


solc_version  = '0.8.26'
vm_version = "cancum"
optimizer_runs = 800
via_ir =false
ffi = true 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
